FIX: typo
PierreCapo/hermine-pierre pull request #1
Opened 2024-09-08 07:25 UTC by tychota

Sadly, my name is not written correctly.
I order to be rgpd compliment I opened this PR.

2024-09-08 09:29 UTC, Almouro requested changes

2024-09-08 09:29 UTC, Almouro commented on src/data.json
> +    "lastname": "Tatitscheff",
Shouldn't it be Typo Tapitscheff

2024-09-10 12:33 UTC, PierreCapo commented
LGTM ready to ship 🚀
@tychota can you add tests associated your PR before merging?

En vrai ultra désolé @tychota @Almouro pour les typos 🙏🙏🙏

2024-09-10 13:15 UTC, Almouro commented
> LGTM ready to ship 🚀 @tychota can you add tests associated your PR before merging?
> 
> En vrai ultra désolé @tychota @Almouro pour les typos 🙏🙏🙏

Pas de soucis haha, j'ai toujours dit que 4 lettres pour faire le son O, c'était trop de toute façon
(Source: j'ai eu des cours de traitement et encodage de l'information)

2024-09-14 08:29 UTC, merged